version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongodb:27017/chatbot-app
    networks:
      - app-network
    command: ["sh", "-c", "npx nestjs-command seed:questions && pnpm start"]

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_WS_URL=http://0.0.0.0:8000
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017" 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
